version: "2"

services:
  prestashop_db:
    image: mysql:5.7
    volumes:
    - prestashop_db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    labels:
      - traefik.enable=false

  prestashop_front:
    depends_on:
    - prestashop_db
    image: prestashop/prestashop
    restart: always
    volumes:
    - prestashop_data:/var/www/html
    labels:
      - traefik.enable=true
      - traefik.backend=prestashop
      - traefik.frontend.rule=Host:127.0.0.1
      - traefik.port=80
      #- traefik.frontend.headers.SSLRedirect=true
      #- traefik.frontend.headers.SSLHost=exemple.com
      #- traefik.frontend.headers.STSSeconds=315360000
      #- traefik.frontend.headers.STSIncludeSubdomains=true
      #- traefik.frontend.headers.STSPreload=true
      #- traefik.frontend.headers.frameDeny=true
      #- traefik.frontend.headers.browserXSSFilter=true
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
    prestashop_db_data: {}
    prestashop_data: {}

